apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-gate
spec:
  selector:
    matchLabels:
      app: prometheus-gate
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-gate
    spec:
      containers:
      - name: gate
        image: github.com/iancoffey/prometheus-gate
        env:
        - name: TARGET_VALUE
          value: "1"
        - name: PROMETHEUS_ENDPOINT
          value: "http://prometheus-system-np.knative-monitoring.svc.cluster.local:8080"
        - name: RANGE_QUERY
          value: kube_deployment_status_replicas{deployment="my-target", namespace="default", service="kube-state-metrics"}
